# Generated by Django 5.1.6 on 2025-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_educationsquali'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('language_used', models.CharField(max_length=100)),
                ('project_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
